### ISSUE TITLE
Include tests in release

### ISSUE THREAD

**Issue by FRidh** [matplotlib/cycler#31] opened 2016-02-17 19:35 UTC
Please include tests in the archives of releases. This makes it easier for packagers to test whether their packaged version works. Thanks!

**Comment by tacaswell** [comment] 2016-02-17 20:53
Duplicate of #21 which we thought we fixed :disappointed: 

Looks like the manifest include the test _running_ script, but not the actual tests.

**Comment by tacaswell** [comment] 2016-02-17 20:54
If you grab the tarball from github instead of pip you will get the expected files.

**Closed** 2016-02-18 08:52 UTC
